//! Build residue left behind by development projects.
//!
//! The rule: a directory is never removed on its name alone. A `target` is only
//! deleted when it sits next to a `Cargo.toml`, a `build` only when the tool that
//! generates it can be identified. Everything listed here is regenerated by the
//! language's own toolchain.

use std::path::{Path, PathBuf};
use std::time::{Duration, SystemTime};

use serde::Serialize;

use super::Ctx;
use crate::sys::{cmd, fsx};

/// Detection rule for one ecosystem.
struct Rule {
    language: &'static str,
    /// Files that identify the root of a project.
    markers: &'static [&'static str],
    /// Extensions that identify the root of a project (`.csproj`…).
    extensions: &'static [&'static str],
    /// Regenerable directories, relative to the project root.
    artifacts: &'static [&'static str],
    /// File that must exist inside the directory to confirm its origin.
    confirm: Option<&'static str>,
    /// The ecosystem's own clean command, run from the project root. `None`
    /// when the tool offers none: removing the directory is then the official
    /// method (`npm ci` and `composer install` rebuild it).
    clean_command: Option<&'static [&'static str]>,
}

/// Every directory listed here is rebuilt by an `install` or a `build`.
const RULES: &[Rule] = &[
    Rule {
        language: "rust",
        markers: &["Cargo.toml"],
        extensions: &[],
        artifacts: &["target"],
        confirm: None,
        clean_command: Some(&["cargo", "clean", "--offline"]),
    },
    Rule {
        language: "node",
        markers: &["package.json"],
        extensions: &[],
        artifacts: &[
            "node_modules",
            ".next",
            ".nuxt",
            ".turbo",
            ".parcel-cache",
            ".svelte-kit",
            ".angular",
            ".astro",
        ],
        confirm: None,
        clean_command: None,
    },
    Rule {
        language: "python",
        markers: &["pyproject.toml", "setup.py", "requirements.txt", "Pipfile"],
        extensions: &[],
        artifacts: &[
            "__pycache__",
            ".pytest_cache",
            ".mypy_cache",
            ".ruff_cache",
            ".tox",
        ],
        confirm: None,
        clean_command: None,
    },
    Rule {
        language: "gradle",
        markers: &["build.gradle", "build.gradle.kts", "settings.gradle"],
        extensions: &[],
        artifacts: &["build", ".gradle"],
        confirm: None,
        clean_command: Some(&["./gradlew", "clean", "--offline"]),
    },
    Rule {
        language: "maven",
        markers: &["pom.xml"],
        extensions: &[],
        artifacts: &["target"],
        confirm: None,
        clean_command: Some(&["mvn", "-o", "-q", "clean"]),
    },
    Rule {
        language: "swift",
        markers: &["Package.swift"],
        extensions: &[],
        artifacts: &[".build"],
        confirm: None,
        clean_command: Some(&["swift", "package", "clean"]),
    },
    Rule {
        language: "dotnet",
        markers: &[],
        extensions: &["csproj", "fsproj", "vbproj", "sln"],
        artifacts: &["bin", "obj"],
        confirm: None,
        clean_command: Some(&["dotnet", "clean", "--nologo", "-v", "q"]),
    },
    Rule {
        language: "php",
        markers: &["composer.json"],
        extensions: &[],
        artifacts: &["vendor"],
        confirm: None,
        clean_command: None,
    },
    Rule {
        language: "elixir",
        markers: &["mix.exs"],
        extensions: &[],
        artifacts: &["_build", "deps"],
        confirm: None,
        clean_command: Some(&["mix", "clean"]),
    },
    Rule {
        language: "dart",
        markers: &["pubspec.yaml"],
        extensions: &[],
        artifacts: &["build", ".dart_tool"],
        confirm: None,
        clean_command: Some(&["flutter", "clean"]),
    },
    Rule {
        language: "zig",
        markers: &["build.zig"],
        extensions: &[],
        artifacts: &["zig-cache", ".zig-cache", "zig-out"],
        confirm: None,
        clean_command: None,
    },
    Rule {
        language: "go",
        markers: &["go.mod"],
        extensions: &[],
        artifacts: &["vendor"],
        confirm: None,
        clean_command: None,
    },
    Rule {
        // A `build` directory is only purged when it holds a CMake cache.
        language: "cmake",
        markers: &["CMakeLists.txt"],
        extensions: &[],
        artifacts: &["build", "cmake-build-debug", "cmake-build-release"],
        confirm: Some("CMakeCache.txt"),
        clean_command: None,
    },
];

/// Recognised languages, for the help text and the `--lang` filter.
pub fn languages() -> Vec<&'static str> {
    let mut names: Vec<&'static str> = RULES.iter().map(|rule| rule.language).collect();
    names.sort_unstable();
    names.dedup();
    names
}

/// A regenerable directory found on disk.
#[derive(Debug, Clone, Serialize)]
pub struct Residue {
    pub language: &'static str,
    /// Directory to remove.
    pub path: PathBuf,
    /// Root of the project that produced it.
    pub project: PathBuf,
    /// Directory name (`target`, `node_modules`…).
    pub kind: String,
    pub bytes: u64,
    /// Days since the last modification.
    pub age_days: u64,
}

/// Search criteria.
#[derive(Debug, Clone)]
pub struct Filter {
    pub root: PathBuf,
    pub max_depth: usize,
    /// Minimum age, in days.
    pub min_age_days: u64,
    /// Languages to keep; empty means all of them.
    pub languages: Vec<String>,
}

/// Directories there is no point descending into.
const SKIPPED: &[&str] = &["Library", "Applications", ".Trash", "Pictures", "Movies"];

/// Walks the tree looking for build residue, without measuring it.
///
/// Sizing is by far the slow part, so it is left to [`measure`]: the caller can
/// then report progress over a known number of directories.
pub fn candidates(filter: &Filter, progress: &mut impl FnMut(&Path)) -> Vec<Residue> {
    let mut found = Vec::new();
    visit(&filter.root, 0, filter, &mut found, progress);
    found
}

/// Fills in the size of one candidate.
pub fn measure(residue: &mut Residue) {
    residue.bytes = fsx::size_of(&residue.path);
}

fn visit(
    dir: &Path,
    depth: usize,
    filter: &Filter,
    found: &mut Vec<Residue>,
    progress: &mut impl FnMut(&Path),
) {
    if depth > filter.max_depth {
        return;
    }

    progress(dir);

    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };

    let mut names = Vec::new();
    let mut subdirs = Vec::new();

    for entry in entries.flatten() {
        let Ok(kind) = entry.file_type() else {
            continue;
        };
        if kind.is_symlink() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_string();
        if kind.is_dir() {
            subdirs.push(name.clone());
        }
        names.push(name);
    }

    // Directories already identified as regenerable are never descended into.
    let mut claimed: Vec<String> = Vec::new();

    for rule in RULES {
        if !filter.languages.is_empty()
            && !filter
                .languages
                .iter()
                .any(|wanted| wanted.eq_ignore_ascii_case(rule.language))
        {
            continue;
        }
        if !rule.matches(&names) {
            continue;
        }

        for artifact in rule.artifacts {
            if !subdirs.iter().any(|name| name == artifact) {
                continue;
            }
            let path = dir.join(artifact);
            if let Some(required) = rule.confirm {
                if !path.join(required).exists() {
                    continue;
                }
            }

            claimed.push((*artifact).to_string());
            let age_days = age(&path).as_secs() / 86_400;
            if age_days < filter.min_age_days {
                continue;
            }

            found.push(Residue {
                language: rule.language,
                kind: (*artifact).to_string(),
                // Measured later, by `measure`.
                bytes: 0,
                path,
                project: dir.to_path_buf(),
                age_days,
            });
        }
    }

    for name in subdirs {
        if name.starts_with('.') || SKIPPED.contains(&name.as_str()) || claimed.contains(&name) {
            continue;
        }
        visit(&dir.join(name), depth + 1, filter, found, progress);
    }
}

impl Rule {
    /// Does the project belong to this language, given the files present?
    fn matches(&self, names: &[String]) -> bool {
        self.markers
            .iter()
            .any(|marker| names.iter().any(|name| name == marker))
            || self.extensions.iter().any(|extension| {
                names
                    .iter()
                    .any(|name| Path::new(name).extension().is_some_and(|e| e == *extension))
            })
    }
}

/// Time since the directory — or its top-level content — was last modified: a
/// `target` that was just compiled into is never considered old.
fn age(path: &Path) -> Duration {
    let mut latest = std::fs::symlink_metadata(path)
        .and_then(|meta| meta.modified())
        .unwrap_or(SystemTime::UNIX_EPOCH);

    if let Ok(entries) = std::fs::read_dir(path) {
        for entry in entries.flatten() {
            if let Ok(modified) = entry.metadata().and_then(|meta| meta.modified()) {
                latest = latest.max(modified);
            }
        }
    }

    SystemTime::now()
        .duration_since(latest)
        .unwrap_or(Duration::ZERO)
}

/// How a directory was emptied.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Method {
    /// Directory removed outright.
    Removed,
    /// The language's tool did the work (`cargo clean`…).
    Toolchain,
    /// The tool left leftovers, so the directory was removed afterwards.
    ToolchainThenRemoved,
}

/// Result of removing one residue.
#[derive(Debug, Clone, Serialize)]
pub struct Removed {
    pub path: PathBuf,
    pub language: &'static str,
    pub bytes: u64,
    pub method: Method,
    /// Command used, when there was one.
    pub command: Option<String>,
    pub error: Option<String>,
}

/// Rule matching a language.
fn rule_for(language: &str) -> Option<&'static Rule> {
    RULES.iter().find(|rule| rule.language == language)
}

/// Clean command available for this residue, when the tool is installed.
fn toolchain_command(residue: &Residue) -> Option<&'static [&'static str]> {
    let command = rule_for(residue.language)?.clean_command?;
    let program = command.first()?;

    // A wrapper (`./gradlew`) must exist in the project, a binary in the PATH.
    let available = if program.starts_with("./") {
        residue
            .project
            .join(program.trim_start_matches("./"))
            .is_file()
    } else {
        cmd::exists(program)
    };

    available.then_some(command)
}

/// Describes the command that would be used, for display.
pub fn planned_command(residue: &Residue) -> Option<String> {
    toolchain_command(residue).map(|command| command.join(" "))
}

/// Removes one directory, optionally through the language's own tool.
pub fn remove_one(residue: &Residue, toolchain: bool, ctx: &Ctx) -> Removed {
    let mut report = Removed {
        path: residue.path.clone(),
        language: residue.language,
        bytes: residue.bytes,
        method: Method::Removed,
        command: None,
        error: None,
    };

    let command = toolchain.then(|| toolchain_command(residue)).flatten();

    if let Some(command) = command {
        report.command = Some(command.join(" "));
        report.method = Method::Toolchain;

        if ctx.dry_run {
            return report;
        }

        if let Err(err) = cmd::run_in(&residue.project, command[0], &command[1..]) {
            report.command = Some(format!("{} — {err}", command.join(" ")));
            report.method = Method::ToolchainThenRemoved;
        } else if residue.path.exists() {
            // `mix clean` and `dotnet clean` only empty part of the directory.
            report.method = Method::ToolchainThenRemoved;
        } else {
            return report;
        }
    }

    if ctx.dry_run {
        return report;
    }

    // Whatever is left: the whole directory, or the tool's leftovers.
    let remaining = fsx::size_of(&residue.path);
    if remaining > 0 || residue.path.exists() {
        if let Err(err) = fsx::remove(&residue.path, false) {
            report.bytes = residue.bytes.saturating_sub(remaining);
            report.error = Some(err.to_string());
        }
    }

    report
}

/// Total size of a list of residues.
pub fn total(residues: &[Residue]) -> u64 {
    residues.iter().map(|residue| residue.bytes).sum()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rules_only_target_relative_directories() {
        for rule in RULES {
            assert!(
                !rule.artifacts.is_empty(),
                "{} has no artifact",
                rule.language
            );
            for artifact in rule.artifacts {
                assert!(!artifact.starts_with('/'), "{artifact} is absolute");
                assert!(!artifact.contains(".."), "{artifact} escapes the project");
                assert!(!artifact.contains('/'), "{artifact} is not a direct child");
            }
            assert!(
                !rule.markers.is_empty() || !rule.extensions.is_empty(),
                "{} has no marker",
                rule.language
            );
        }
    }

    #[test]
    fn rust_projects_are_recognised_by_their_manifest() {
        let rust = RULES.iter().find(|r| r.language == "rust").unwrap();
        assert!(rust.matches(&["Cargo.toml".to_string(), "src".to_string()]));
        assert!(!rust.matches(&["target".to_string()]));
    }

    #[test]
    fn dotnet_projects_are_recognised_by_extension() {
        let dotnet = RULES.iter().find(|r| r.language == "dotnet").unwrap();
        assert!(dotnet.matches(&["App.csproj".to_string()]));
        assert!(!dotnet.matches(&["App.txt".to_string()]));
    }

    #[test]
    fn clean_commands_are_offline_and_non_interactive() {
        for rule in RULES {
            let Some(command) = rule.clean_command else {
                continue;
            };
            assert!(command.len() >= 2, "{}: incomplete command", rule.language);
            assert!(
                command.contains(&"clean"),
                "{}: the command does not clean",
                rule.language
            );
        }
    }

    #[test]
    fn languages_are_listed_alphabetically() {
        let names = languages();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        assert_eq!(names, sorted);
    }
}
